//@version=5

indicator('Vertical Horizontal Filter', shorttitle='VHF')
len_vhf = input.int(title='VHF Length', defval=28, minval=1)
HCP = ta.highest(close, len_vhf)
LCP = ta.lowest(close, len_vhf)
MCP = math.sum(math.abs(close - close[1]), len_vhf)
VHF = (HCP - LCP) / MCP
thVHF = input.float(title='VHF threshold', defval=0.12, minval=0.1, maxval=0.2, step=0.01)
abVHF = VHF > thVHF
upVHF = VHF > VHF[1]
onVHF = abVHF and upVHF
// plot(VHF, title='VHF', linewidth=2, color=color.new(color.blue, 0))
// hline(0.2, title="Min Line", color=#787B86, linestyle=hline.style_dotted)