//@version=5
//creator:Adam White Author:@fr3762 KIVANÇ on twitter

indicator('Vertical Horizontal Filter', shorttitle='VHF')
length = input.int(title='Length', defval=28, minval=1)
showema = input(false, title='Show EMA?')
emalength = input.int(title='Ema Length', defval=14, minval=1)
fiyat = input(title='Source', defval=close)
HCP = ta.highest(fiyat, length)
LCP = ta.lowest(fiyat, length)
MCP = math.sum(math.abs(fiyat - fiyat[1]), length)
VHF = (HCP - LCP) / MCP
plot(VHF, title='VHF', linewidth=2, color=color.new(color.red, 0))
ema_1 = ta.ema(VHF, emalength)
plot(showema ? ema_1 : na, linewidth=1, color=color.new(color.blue, 0))